# volt.toml (Lapce plugin definition)
name = "eclipse-theme"
display-name = "Eclipse theme"
description = "Lapce theme similar to Eclipse light. Theme name: 'Eclipse Light'."
icon = "assets/icon.png"
version = "0.0.3"
author = "Lucas Persson"
repository = "https://github.com/Lucas3oo/lapce-eclipse-theme"
color-themes = ["eclipse-light.toml"]
